spring:
  profiles:
    active: kafkaAndRedisWithSpringBootAppProfile
  application:
    name: KafkaAndRedisWithSpringBootApplication

kafka:
  bootstrap-servers: ${bootstrapServers}
  topic:
    spotify: ${spotifyTopic}
