spring:
  profiles:
    active: kafkaAndRedisWithSpringBootAppProfile
  application:
    name: KafkaAndRedisWithSpringBootApplication

kafka:
  bootstrap-servers: ${bootstrapServers}
  topic:
    spotify: ${spotifyTopic}

server:
  servlet:
    context-path: /kafka_service
  port: ${kafkaServiceAppPort}