spring:
  profiles:
    active: kafkaAndRedisWithSpringBootAppProfile
  application:
    name: KafkaAndRedisWithSpringBootApplication

kafka:
  bootstrap-servers: ${bootstrapServers}
  topic:
    spotify: ${spotifyTopic}
    playlist: ${playlistTopic}
    artist: ${artistTopic}
    genre: ${genreTopic}
  service:
    base-url: ${songServiceBaseUrl}

server:
  servlet:
    context-path: /kafka_service
  port: ${kafkaServiceAppPort}